language: cpp
compiler: gcc
cache: apt
before_install: sudo apt-get update
install: sudo apt-get install libboost-system-dev liblua5.2-dev libgmp3-dev libmysqlclient-dev
before_script: mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Release ..
script: make
